import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/auth";
import { supabase } from "@/lib/supabase";
import { z } from "zod";
import { randomUUID } from "crypto";

const createSchema = z.object({
  adSetId: z.string(),
  name: z.string().min(1),
  identityPage: z.string().default(""),
  identityInstagram: z.string().default(""),
  format: z.enum(["SINGLE_IMAGE_VIDEO", "CAROUSEL", "COLLECTION"]).default("SINGLE_IMAGE_VIDEO"),
  primaryText: z.string().default(""),
  headline: z.string().default(""),
  description: z.string().default(""),
  mediaUrls: z.array(z.string()).default([]),
  cta: z.enum(["LEARN_MORE", "SHOP_NOW", "SIGN_UP", "BOOK_NOW", "CONTACT_US", "DOWNLOAD", "GET_OFFER", "GET_QUOTE", "SUBSCRIBE", "WATCH_MORE"]).default("LEARN_MORE"),
  destinationUrl: z.string().default(""),
});

export async function POST(req: NextRequest) {
  const session = await auth();
  if (!session) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const body = await req.json();
  const parsed = createSchema.safeParse(body);
  if (!parsed.success) return NextResponse.json({ error: parsed.error.flatten() }, { status: 400 });

  const d = parsed.data;

  // Get adset & campaign for simulation
  const { data: adSet } = await supabase
    .from("AdSet")
    .select("*, campaign:Campaign(*)")
    .eq("id", d.adSetId)
    .single();

  if (!adSet) return NextResponse.json({ error: "Ad set not found" }, { status: 404 });

  const { data: ad, error: adError } = await supabase
    .from("Ad")
    .insert({
      id: randomUUID(),
      adSetId: d.adSetId,
      name: d.name,
      identityPage: d.identityPage,
      identityInstagram: d.identityInstagram,
      format: d.format,
      primaryText: d.primaryText,
      headline: d.headline,
      description: d.description,
      mediaUrls: JSON.stringify(d.mediaUrls),
      cta: d.cta,
      destinationUrl: d.destinationUrl,
      status: "IN_REVIEW",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString()
    })
    .select()
    .single();

  if (adError) return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });

  // Update parent adset & campaign to IN_REVIEW
  await supabase.from("AdSet").update({ status: "IN_REVIEW" }).eq("id", d.adSetId);
  await supabase.from("Campaign").update({ status: "ACTIVE" }).eq("id", adSet.campaignId);

  // Note: Initial metrics are no longer generated here. 
  // They will be generated by the simulator tick engine once the Ad is approved (ACTIVE).

  return NextResponse.json(ad, { status: 201 });
}
